version: '3'
services:
  mongo:
    image: mongo:3.4.4
    container_name: mongodb
    volumes:
        - /opt/adidas
    ports:
      - "27017:27017"

  #FRONTEND WITH NGNIX FOR REVERSE PROXY
  frontend-proxy:
    image: addidas_frontend/frontend-proxy:0.0.1-SNAPSHOT
    container_name: frontend-proxy
    depends_on:
      - adidasApi
    links:
      - adidasApi
    ports:
      - "80:8080"

  adidasApi:
    image: modelname:0.0.1-SNAPSHOT
    container_name: modelname
    depends_on:
      - mongo
    ports:
      - "5000:5000"

